### PR TITLE
updates to community theme

### PR DESCRIPTION
**Pull request by clausmullie**
Updating to community theme straight to the main branch (see #1058)

### CODE REVIEW

**Comment by clausmullie** [comment]
Build locally, fails here. 

I see we updated to actions/checkout@v4 with 0ab837060a60e4eefe99e6104eec7d5a3155ddcd and more importantly, in `.github/workflows/test.yml` updated ruby version from 2.7 -> 3.1 with 9dca31f41cb5b7b723c54b0ad59f05b62ce46d37

I'm assuming it's this fix that would need to be implemented?

**Comment by clausmullie** [comment]
Theme already live as github pages builds from the develop branch.

**Comment by ericherman** [comment]
> Theme already live as github pages builds from the develop branch.

My memory might be wrong, but I believe this reflects a difference in the configurations of the repositories.

Regardless, it is worth considering if this is the desired behaviour, as the threshold for merging to develop is lower and likely far less rigorous than merging to main or making a release.
I suggest that this should be either an issue in the repository or perhaps a discussion topic in the next monthly call; I don't know which is best.

**Comment by Ainali** [comment]
> I suggest that this should be either an issue in the repository or perhaps a discussion topic in the next monthly call; I don't know which is best.

Agreed, a conscious decision would be great.

**Pull request closed without merging**
